image: "rustlang/rust:nightly"

variables:
  CARGO_HOME: ".cargo/"

default:
  before_script:
    - rustc --version
    - cargo --version
    - apt-get update -qq && apt-get install libudev-dev libasound2-dev alsa-utils -qq
    - curl --proto '=https' --tlsv1.2 -sSf https://just.systems/install.sh | bash -s -- --to /usr/local/bin
    - export PATH="$CI_PROJECT_DIR/.cargo/bin:$PATH"

cache:
  paths:
    - target/
    - .cargo/

stages:
  - test
  - build
  - release

publish-beta:
  rules:
    - if: '$CI_COMMIT_TAG =~ /^\d+\.\d+\.\d+b\-\d+/' # A specific tag with 'X.Y.Zb-V' pattern is created
  stage: release
  script:
    - just publish-beta $CI_COMMIT_TAG
    - just publish-beta-win $CI_COMMIT_TAG
  artifacts:
    paths:
      - dist

publish:
  rules:
    - if: '$CI_COMMIT_TAG =~ /^\d+\.\d+\.\d+b\-\d+/'
      when: never
    - if: '$CI_COMMIT_TAG =~ /^\d+\.\d+\.\d+/' # A specific tag with 'X.Y.Z' pattern is created
  stage: release
  script:
    - just publish $CI_COMMIT_TAG
    - just publish-win $CI_COMMIT_TAG
  artifacts:
    paths:
      - dist

test-code:
  stage: test
  script:
    - rustup component add rustfmt
    - cargo fmt -- --check
    - rustup component add clippy
    - cargo install gitlab_clippy
    - cargo install junitify
    - cargo test -- --format=json -Z unstable-options --report-time | junitify --out $CI_PROJECT_DIR/tests/
    # need to build before running clippy for some reson (took me TWENTY MINUTES to figure this out)
    - cargo build
    - cargo clippy -- -W clippy::pedantic --message-format=json | gitlab-clippy > gl-code-quality-report.json
  artifacts:
    when: always
    paths:
      - tests/*.xml
    reports:
      junit: tests/*.xml
      codequality: gl-code-quality-report.json



publish-macos:
  rules:
    - if: '$CI_COMMIT_TAG =~ /^\d+\.\d+\.\d+b\-\d+/'
      when: never
    - if: '$CI_COMMIT_TAG =~ /^\d+\.\d+\.\d+/' # A specific tag with 'X.Y.Z' pattern is created
  stage: release
  script:
    - just publish $CI_COMMIT_TAG
  artifacts:
    paths:
      - dist
  tags:
    - macos

publish-beta-macos:
  rules:
    - if: '$CI_COMMIT_TAG =~ /^\d+\.\d+\.\d+b\-\d+/'
  stage: release
  script:
    - just publish-beta $CI_COMMIT_TAG
  artifacts:
    paths:
      - dist
  tags:
    - macos
