image: "rust:latest"

default:
  before_script:
    - rustc --version 
    - cargo --version
    - apt-get update -qq && apt-get install libudev-dev libasound2-dev alsa-utils -qq
  artifacts:
    paths:
      - target/release/ppan

stages:
  - test
  - build
  - release

compile:
  stage: build
  script:
    - cargo build --release

publish-beta:
  rules:
    - if: '$CI_COMMIT_TAG =~ /^\d+\.\d+\.\d+b\-\d+/' # A specific tag with 'X.Y.Zb-V' pattern is created
  stage: release
  script:
    - curl -L -o butler.zip https://broth.itch.ovh/butler/linux-amd64/LATEST/archive/default
    - unzip butler.zip
    - chmod +x butler
    - ./butler -V
    - cargo build --release
    - mkdir -p dist
    - cp target/release/ppan dist
    - mkdir -p assets
    - cp -r assets dist/
    - "butler push dist jabster28/ppan:linux-32bit-beta --userversion $CI_COMMIT_TAG"

publish:
  rules:
    - if: '$CI_COMMIT_TAG =~ /^\d+\.\d+\.\d+b\-\d+/'
      when: never
    - if: '$CI_COMMIT_TAG =~ /^\d+\.\d+\.\d+/' # A specific tag with 'X.Y.Z' pattern is created
  stage: release
  script:
    - curl -L -o butler.zip https://broth.itch.ovh/butler/linux-amd64/LATEST/archive/default
    - unzip butler.zip
    - chmod +x butler
    - ./butler -V
    - cargo build --release
    - mkdir -p dist
    - cp target/release/ppan dist
    - mkdir -p assets
    - cp -r assets dist/
    - "butler push dist jabster28/ppan:linux-32bit-stsable --userversion $CI_COMMIT_TAG"

test-code:
  stage: test
  script:
    - cargo test
    - cargo install cargo-tarpaulin
    - cargo tarpaulin --ignore-tests

lint-code:
  stage: test
  script:
    - rustup component add clippy
    - cargo clippy -- -D warnings
    
format-code:
  stage: test
  script:
    - rustup component add rustfmt
    - cargo fmt -- --check