[package]
name = "ppan"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cgmath = "0.18.0"
derive-new = "0.5.9"
ggez = "0.7.0"
glam = "0.20.5"
macroquad = "0.3"
ggez-egui = "0.1.7"
