[package]
name = "ppan"
version = "0.0.1"
edition = "2021"
description = "pong, but a little more interesting."

[package.metadata.bundle]
identifier = "io.ppan"
category = "public.app-category.arcade-games"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cgmath = "0.18.0"
derive-new = "0.5.9"
ggez = "0.7.0"
glam = "0.20.5"
macroquad = "0.3"
ggez-egui = "0.1.7"
